config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#wishlist"

  resources :foursquare, only: [] do
    collection do
      get :callback

      post :authenticate
      delete :logoff
    end
  end

  resources :home, only: [:index] do
    collection do
      post :add_venue

      delete :remove_venue
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :foursquare_id, type: Integer
  field :first_name, type: String
  field :last_name, type: String
  field :photo_thumb, type: String
  field :gender, type: String
  field :bio, type: String

  embeds_many :venues
end

app/models/venue.rb
class Venue
  include Mongoid::Document
  field :venue_id, type: String
  field :name, type: String
  field :photo, type: String

  embedded_in :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_logged_in?
  helper_method :authenticate_user


  protected

  def current_user
    session["current_user"] || {}
  end

  def user_logged_in?
    session["current_user"].blank? ? false : true
  end

  def authenticate_user
    redirect_to home_index_path unless user_logged_in?
  end
end

app/controllers/foursquare_controller.rb
class FoursquareController < ApplicationController
    def authenticate
        domain = request.host
        domain << (request.port == "80" ? "" : ":#{request.port}")

        redirect_to "https://foursquare.com/oauth2/authenticate?client_id=#{Foursquare::CLIENT_ID}&response_type=code&redirect_uri=http://#{domain}/foursquare/callback"
    end

    def callback
        domain = request.host
        domain << (request.port == "80" ? "" : ":#{request.port}")

        response = RestClient.get "https://foursquare.com/oauth2/access_token?client_id=#{Foursquare::CLIENT_ID}&client_secret=#{Foursquare::CLIENT_SECRET}&grant_type=authorization_code&code=#{params['code']}&redirect_uri=http://#{domain}/foursquare/callback", {content_type: :json, accept: :json}
        session["access_token"] = JSON.parse(response.body)["access_token"]

        login_user
        redirect_to root_path
    end

    def logoff
        reset_session
        redirect_to root_path
    end

    private

    def login_user
        @self = get_self
        @user = User.find_by foursquare_id: @self["id"]
        
        if @user.blank?
            @user = User.create foursquare_id: @self["id"], first_name: @self["firstName"], last_name: @self["lastName"], gender: @self["gender"], bio: @self["bio"], photo_thumb: @self["photo"]["prefix"] + "50x50" + @self["photo"]["suffix"]
        end

        session["current_user"] = @user
    end

    def get_self
        response = RestClient.get "https://api.foursquare.com/v2/users/self?oauth_token=#{session['access_token']}&v=#{Foursquare::VERSION_DATE}", {content_type: :json, accept: :json}
        JSON.parse(response.body)['response']['user']
    end
end

#131944567

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user, except: [:index]
  before_action :set_user, except: [:index]

  def index
  end

  def wishlist
    @venues = get_recent_venues
    @wishlist = @user.venues
  end

  def add_venue
    @venue = Venue.new venue_id: venue_params[:venue_id], name: venue_params[:name], photo: get_venue_photo(venue_params[:venue_id])
    @user.venues << @venue
    @user.save

    redirect_to root_path
  end

  def remove_venue
    @user.venues.find_by(venue_id: venue_params[:venue_id]).destroy
    
    redirect_to root_path
  end


  protected

  def get_recent_venues
    recent_response = JSON.parse(RestClient.get("https://api.foursquare.com/v2/checkins/recent?oauth_token=#{session['access_token']}&v=#{Foursquare::VERSION_DATE}", {content_type: :json, accept: :json}).body)['response']['recent']
    recent_json = recent_response.map do |recent|
      photos_response = JSON.parse(RestClient.get("api.foursquare.com/v2/venues/#{recent['venue']['id']}/photos?oauth_token=#{session['access_token']}&v=#{Foursquare::VERSION_DATE}", {content_type: :json, accept: :json}).body)['response']['photos']['items']
      recent["venue"]["photo"] = photos_response.first['prefix'] + '300x400' + photos_response.first['suffix']
      recent
    end
  end

  def get_venue_photo(id)
    photos_response = JSON.parse(RestClient.get("api.foursquare.com/v2/venues/#{id}/photos?oauth_token=#{session['access_token']}&v=#{Foursquare::VERSION_DATE}", {content_type: :json, accept: :json}).body)['response']['photos']['items']
    photos_response.first['prefix'] + '300x400' + photos_response.first['suffix']
  end

  def venue_params
    params.permit(:venue_id, :name)
  end

  def set_user
    @user = User.find_by foursquare_id: current_user['foursquare_id']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foursquare_helper.rb
module FoursquareHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-login">
    <a href="<%= authenticate_foursquare_index_path %>" class="btn amber darken-1" data-method="post">Login with Foursquare</a>
</div>

app/views/home/wishlist.html.erb
<% unless @wishlist.blank? %>
    <div class="row">
        <h1 class="header orange-text">Wishlist</h1>
    </div>
    <div class="row">
        <% @wishlist.each do |wish| %>
            <div class="col s12 m3">
                <div class="card">
                    <div class="card-image">
                        <img src="<%= wish['photo']%>" />
                        <a href="
                        <%= remove_venue_home_index_path(venue_id: wish['venue_id']) %>" data-method="delete" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">remove</i></a>
                    </div>
                    <div class="card-content">
                        <b><%= wish["name"].to_s %></b>
                    </div>
                </div>
            </div>
            <% end %>
    </div>
    <% end %>
        <div class="row">
            <h1 class="header orange-text">Recent venues</h1>
        </div>
        <div class="row">
            <% wishlist_ids = @wishlist.reduce([]) {|arr, cur| arr << cur['venue_id']} %>
                <% @venues.select {|venue| !wishlist_ids.include?(venue['venue']['id'])}.each do |venue| %>
                    <div class="col s12 m6 l3">
                        <div class="card">
                            <div class="card-image">
                                <img src="<%= venue['venue']['photo']%>" />
                                <a href="<%= add_venue_home_index_path(venue_id: venue['venue']['id'], name: venue['venue']['name']) %>" data-method="post"
                                    class="btn-floating halfway-fab waves-effect waves-light teal"><i class="material-icons">add</i></a>
                                <img src="<%= venue['user']['photo']['prefix']%>64x64<%= venue['user']['photo']['suffix']%>" class="floating-halfway-fab-img"
                                />
                            </div>
                            <div class="card-content">
                                <b><%= venue["venue"]["name"].to_s %></b>
                            </div>
                        </div>
                    </div>
                    <% end %>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DesafioJaya</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application' %>
          <%= javascript_pack_tag 'general' %>
            <%= stylesheet_pack_tag 'application' %>

              <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
  <% if user_logged_in? %>
    <ul id="dropdown1" class="dropdown-content">
      <li>
        <a href="<%= logoff_foursquare_index_path %>" data-method="delete">Logoff</a>
      </li>
    </ul>
    <nav class="amber darken-1">
      <div class="nav-wrapper container">
        <a href="#!" data-activates="dropdown1" class="right dropdown-button">
          <%= current_user["first_name"] + " " + current_user["last_name"] %>
            <i class="material-icons right">arrow_drop_down</i>
        </a>

        <img src="<%= current_user['photo_thumb'].to_s %>" class="profile-img right" />
      </div>
    </nav>
    <% end %>
      <div class="container">
        <%= yield %>
      </div>
</body>

</html>